# This workflow runs a test build to make sure everything compiles properly
name: Test Build

on:
  # Run on pull requests
  pull_request:
    branches: ['master']
  
  # Run when requested manually
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Test static site build
        run: npm run build:static
      
      - name: Test static GitHub Pages build
        run: |
          # Extract the repository owner and name from GITHUB_REPOSITORY
          GITHUB_OWNER=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 1)
          GITHUB_REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)
          
          # Run the build with repository information
          BASE_URL=/$GITHUB_REPO_NAME/ GITHUB_OWNER=$GITHUB_OWNER GITHUB_REPO_NAME=$GITHUB_REPO_NAME npm run build:static:github
